[package]
name = "rust_kvs"
version = "0.1.0"
authors = ["github.com/c-werner"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
serde = "1.0.114"